name: Frontend QA Env Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "${{ contains(fromJson('["PushEvent"]'), github.event) }}"