name: Frontend QA Env Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    if: contains(fromJson('["PushEvent"]'), github.event.type)
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo github.event
